import { describe, expect, it, vi } from 'vitest';
import { STARTER_CARDS, STARTER_DECK_TITLE } from '../data/starterDeck';

vi.mock('../services/database/dbService', () => ({
  dbService: {
    createDeck: vi.fn(async (_userId: string, title: string) => ({ id: 'deck-1', title })),
    saveCards: vi.fn(async (_userId: string, cards: unknown[]) => cards),
  },
}));

vi.mock('../services/api/groqService', () => ({
  generateDeckFromTopic: vi.fn(async (topic: string) => ({
    title: `Deck: ${topic}`,
    description: 'Generated by AI',
    cards: [
      { question: 'Q1?', answer: 'A1', difficulty: 'easy' },
      { question: 'Q2?', answer: 'A2', difficulty: 'medium' },
    ],
  })),
}));

vi.mock('../../services/study/srs', () => ({
  getInitialCardState: vi.fn((_deckId: string, front: string, back: string) => ({
    front,
    back,
    deckId: _deckId,
    nextReview: Date.now() - 1,
  })),
}));

const { createTopicDeck } = await import('../services/decks/topicDeckService');
const { dbService } = await import('../services/database/dbService');

describe('createTopicDeck', () => {
  it('uses the AI deck for a real topic and seeds every card', async () => {
    const { deck, cards } = await createTopicDeck('user-1', 'Spanish basics');

    expect(dbService.createDeck).toHaveBeenCalledWith(
      'user-1',
      'Deck: Spanish basics',
      'Generated by AI',
    );
    expect(deck.id).toBe('deck-1');
    expect(cards).toHaveLength(2);
  });

  it('degenerates to the offline starter deck for an empty topic', async () => {
    const { deck, cards } = await createTopicDeck('user-1', '   ');

    expect(dbService.createDeck).toHaveBeenCalledWith(
      'user-1',
      STARTER_DECK_TITLE,
      expect.any(String),
    );
    expect(deck.title).toBe(STARTER_DECK_TITLE);
    expect(cards).toHaveLength(STARTER_CARDS.length);
  });

  it('seeds each card against the new deck id', async () => {
    const { cards } = await createTopicDeck('user-1', 'Spanish basics');

    for (const card of cards as Array<{ deckId: string }>) {
      expect(card.deckId).toBe('deck-1');
    }
  });
});